name = "SymbolicGA"
uuid = "be1275fb-6550-422f-8b88-a5943ccecfb8"
authors = ["Cédric Belmant"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"

[compat]
Combinatorics = "1.0.2"
julia = "1.8"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
